openapi: "3.0.2"
info:
  title: Payment & Subscription API
  version: "1.0"
servers:
  - url: https://localhost:8080/v1
paths:
  /users:
    get:
      description: "Return details about /users"
      operationId: "getUsers"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: "bad request"
        "404":
          description: "users not found"
components:
  schemas:
    User:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        username:
          type: "string"
        subscriptionStatus:
          type: "boolean"
        subscriptionType:
          type: "string"
        email:
          type: "string"
    ApiResponse:
      type: "object"
      properties:
        code:
          type: "integer"
          format: "int64"
        type:
          type: "string"
        message:
          type: "string"
